query AdminChildDetail($id: Int!) {
  child(id: $id) {
    id
    firstName
    lastName
    birthDate
    picture
    healthRecord
    group {
      id
      name
    }
    parents {
      id
      first_name
      last_name
      avatar
    }
  }
}
