query AdminChildren {
  children {
    id
    firstName
    lastName
    birthDate
    picture
    healthRecord
    group {
      id
      name
    }
    parents {
      id
      first_name
      last_name
      email
      phone
    }
  }
}

mutation DeleteChild($id: Int!) {
  deleteChild(id: $id)
}
