# Modifie les infos d'un enfant existant (nom, date de naissance, groupe, dossier de santé...)
# Utilisé dans : children/[id]/edit.tsx (sauvegarde du formulaire edit enfant)
mutation UpdateChild($id: Int!, $data: UpdateChildInput!) {
  updateChild(id: $id, data: $data) {
    id
    firstName
    lastName
    birthDate
    picture
    healthRecord
    group {
      id
      name
    }
  }
}
