services:
  testDB:
    image: postgres:18.1-alpine3.23
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 10
    stop_grace_period: 1s
    restart: always
    tmpfs: /var/lib/postgresql
    ports:
      - 5433:5432

  backend:
    stop_grace_period: 0s
    env_file:
      - ./.env  # prend le .env du dossier actuel (e2e-tests)
    build: ../backend
    ports:
      - 4000:4000
    volumes:
      - ../backend/src:/app/src
    environment:
      - DB_HOST=testDB  # le host est le nom du conteneur de la BDD soit 'testDB' ici
      - TEST_DB_PORT=5432  # on doit utiliser le port 5432 car c'est le port utilisé par le conteneur 'testDB'
    depends_on:
      testDB:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "echo 'test'"]
      interval: 5s
      timeout: 3s
      retries: 15

  frontend:
    stop_grace_period: 0s
    build: '../frontend'
    environment:
      - NEXT_PUBLIC_GRAPHQL_API_URL=http://localhost:4000
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy