name: Compile and push client and server to prod environment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  client-tests:
    uses: Denis-PATILLOT/cda-nov25-p2-g2/.github/workflows/test-frontend.yml@main

  server-tests:
    uses: Denis-PATILLOT/cda-nov25-p2-g2/.github/workflows/test-backend.yml@main

  e2e-tests:
    uses: Denis-PATILLOT/cda-nov25-p2-g2/.github/workflows/e2e-tests.yml@main

  build-and-push-server:
    needs:
        - server-tests
    uses: Denis-PATILLOT/cda-nov25-p2-g2/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: den123456/babyboard-back:prod

  build-and-push-client:
    needs:
      - client-tests
    uses: Denis-PATILLOT/cda-nov25-p2-g2/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: den123456/babyboard-front:prod

  notify-vps:
    needs:
      - build-and-push-server
      - build-and-push-client
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook on VPS
        run: |
          curl -X POST \
            -H "X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}" \
            https://ops.babyboard.duckdns.org/hooks/redeploy-babyboard-prod